version: '3.8'

services:
  telegram-bot:
    build: .
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_NAME: vocabulary_db
      DB_USER: vocabulary_user
      DB_PASSWORD: vocabulary_password
      PYTHONUNBUFFERED: 1

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: vocabulary_db
      POSTGRES_USER: vocabulary_user
      POSTGRES_PASSWORD: vocabulary_password
    volumes:
      - words_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vocabulary_user -d vocabulary_db"]
      interval: 5s
      timeout: 5s

volumes:
  words_postgres_data: